cuda_config:
  cudnn_deterministic: True
  cudnn_benchmark: True
  cuda_visible_devices: "0"
  world_size: 1
  port: "12001"

model_param:
  img_size: 32
  patch_size: 4
  num_classes: 64
  global_pool: ""
  embed_dim: 192
  depth: 12
  num_heads: 12
  mlp_ratio: 2
  class_token: False

optim:
  optim_name: Adam
  optim_param:
    lr: 0.001
    weight_decay: 0.00005

scheduler:
  # scheduler_name: MultiStepLR
  # scheduler_param:
  #   milestones: [10, 30]
  #   gamma: 0.1
  scheduler_name: CosineAnnealingLR
  scheduler_param:
    T_max: 100

use_warmup: True
warmup_param:
  multiplier: 1
  total_epoch: 3

mode: pretrain
dataset: CIFAR10
epochs: 100
batch_size: 128
num_workers: 0
log_freq: 15
# log_img_epoch: 100
save_epoch: 5
eval_epoch: 5
amp: False